# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 26 May 2014 02:45:13 +0000
*               @ALL          1
*               @user         8
