<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 26 May 2014 02:45:13 +0000
 */
$conf['title'] = 'Ways\' Storium';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-nc-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
